apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-2-nginx
  template:
    metadata:
      labels:
        app: app-2-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: my-app-2
        ports:
        - containerPort: 80
      volumes:
      - name: my-app-2
        configMap:
          name: app2-html-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: app2-nginx-server
spec:
  type: ClusterIP
  selector:
    app: app-2-nginx
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-html-configmap
data:
  index.html: |
    <head><title>app2</title></head>
    <body>
        <p>This is app2.</p>
        <br>
        <p style="color:red">Welcome.</p>
    </body>