apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1-nginx
  template:
    metadata:
      labels:
        app: app-1-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: my-app
        ports:
        - containerPort: 80
      volumes:
      - name: my-app
        configMap:
          name: app1-html-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: app1-nginx-server
spec:
  type: ClusterIP
  selector:
    app: app-1-nginx
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-html-configmap
data:
  index.html: |
    <head><title>app1</title></head>
    <body>
        <p>This is app1.</p>
        <br>
        <p style="color:blue">Welcome.</p>
    </body>