Vagrant.require_version ">= 2.4.4"

BOX = "koalephant/debian12"
BOX_URL = "https://boxes.storage.koalephant.com/debian12/1.4.0/amd64/virtualbox.box"
SCONFIG_NAME = "muguveliS"
WRCONFIG_NAME = "muguveliSW"
SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
    config.vm.define SCONFIG_NAME do |server|
        server.vm.hostname = SCONFIG_NAME
        server.vm.box = BOX
        server.vm.box_url = BOX_URL
        server.vm.network "private_network", ip: SERVER_IP
        server.vm.network "forwarded_port", guest: 6443, host: 6443
        server.vm.provider "virtualbox" do |vb|
            vb.name = SCONFIG_NAME
            vb.cpus = 1
            vb.memory = "1024"
        end
        server.vm.provision "shell", path: "scripts/setup_server.sh", args: [SERVER_IP]
    end


    config.vm.define WRCONFIG_NAME do |worker|
        worker.vm.hostname = WRCONFIG_NAME
        worker.vm.box = BOX
        worker.vm.box_url = BOX_URL
        worker.vm.network "private_network", ip: WORKER_IP
        worker.vm.provider "virtualbox" do |vb|
            vb.name = WRCONFIG_NAME
            vb.cpus = 1
            vb.memory = "1024"
        end
        worker.vm.provision "shell", path: "scripts/setup_worker.sh", args: [SERVER_IP]
    end
end
